name: manual

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Boostrap Gradle Memory
        shell: bash
        run: |
         wget https://raw.githubusercontent.com/PaulWoitaschek/Voice/refs/heads/main/scripts/gradle_bootstrap.sh
         chmod +x gradle_bootstrap.sh
         bash gradle_bootstrap.sh
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Try buildingv
        run: |
          wget https://github.com/monsivamon/twitter-apk/releases/download/11.86.0-release.0/x-piko-v11.86.0-release.0.apk -O piko.apk
          #wget https://github.com/kareemlukitomo/morphe-patches/releases/download/v26.4.30-d38bd3/patches-26.4.30-d38bd3.mpp -O patches.mpp
          #wget https://github.com/kareemlukitomo/morphe-patches/releases/download/v26.4.30-d38bd3/patches-26.4.30-d38bd3.mpp
          wget https://github.com/MorpheApp/morphe-cli/releases/download/v1.8.0/morphe-cli-1.8.0-all.jar -O morphe.jar
          java -jar morphe.jar patch piko.apk -p https://github.com/kareemlukitomo/morphe-patches --striplibs=arm64-v8a --unsigned --purge -e='Disable Twitter PairIP startup checks' --exclusive --continue-on-error -f
